name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.7.3'

    - name: Build Documentation
      run: swift build --target swift-srt --configuration debug

    - name: Generate DocC Archive
      run: swift package --disable-sandbox preview-documentation --target swift-srt --output-path build/docs

    - name: Transform DocC Archive for Static Hosting
      run: |
        $(xcrun --find docc) process-archive transform-for-static-hosting build/docs/swift-srt.doccarchive \
        --output-path build/site \
        --hosting-base-path swift-srt/documentation/swiftsrt

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/site
