name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: msft-github/msbuild@v1

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.7'

    - name: Build project
      run: swift build --configuration debug

    - name: Generate DocC Archive
      run: |
        swift package \
        --disable-sandbox \
        generate-documentation \
        --target swift-srt \
        --output-path ./docs

    - name: Publish DocC
      uses: MakeSchool-Tutorials/Static-Docc-Site-Generator@v1
      with:
        docc-archive-path: ./docs
        hosting-base-path: /swift-srt/documentation/swiftsrt
        gh-pages-branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
