name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # Using v2 instead of v3

    - name: Set up Swift
      uses: fwal/setup-swift@v1

    - name: Build
      run: swift build --target swift-srt --configuration debug

    - name: Generate documentation
      run: |
        swift package --allow-writing-to-directory ./docs \
        generate-documentation --target swift-srt --output-path ./swift-srt.doccarchive

    - name: Generate static documentation
      run: $(xcrun --find docc) process-archive transform-for-static-hosting ./swift-srt.doccarchive --output-path ./docs --hosting-base-path /swift-srt/documentation/swiftsrt
