name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Swift
      uses: fwal/setup-swift@v2
      with:
        swift-version: '5.7'

    - name: Build project
      run: swift build --configuration debug

    - name: Generate DocC Archive
      run: |
        swift package \
        --disable-sandbox \
        generate-documentation \
        --target swift-srt \
        --output-path ./docs

    - name: Transform for Static Hosting
      run: |
        $(xcrun --find docc) process-archive transform-for-static-hosting \
        ./docs/SwiftSrt.doccarchive \
        --output-path ./site \
        --hosting-base-path swift-srt/documentation/swiftsrt

    - name: Commit and Push Documentation
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update generated documentation"
        git push
