name: Build and Publish Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.7.3'
      
      - name: Build project
        run: swift build --target swift-srt --configuration debug
      
      - name: Generate DocC documentation
        run: swift package --disable-sandbox preview-documentation --target swift-srt --output-path build/SwiftSrt.doccarchive

      - name: Transform for static hosting
        run: |
          $(xcrun --find docc) process-archive \
          transform-for-static-hosting build/SwiftSrt.doccarchive \
          --output-path docs \
          --hosting-base-path swift-srt/documentation/swiftsrt

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
