name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Swift
      uses: fwal/setup-swift@v2
      with:
        swift-version: '5.9'

    - name: Build project
      working-directory: ./swift-srt
      run: swift build --configuration debug

    - name: Generate DocC Archive
      working-directory: ./swift-srt
      run: |
        xcodebuild docbuild \
        -scheme swift-srt \
        -destination 'platform=macOS' \
        -derivedDataPath build

    - name: Transform DocC for Static Hosting
      working-directory: ./swift-srt
      run: |
        $(xcrun --find docc) process-archive \
        transform-for-static-hosting build/Build/Products/Debug/SwiftSrt.doccarchive \
        --output-path ./docs \
        --hosting-base-path /swift-srt/documentation/swiftsrt

    - name: Commit and Push Documentation
      working-directory: ./swift-srt
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs
        git commit -m 'Update generated documentation'
        git push
