name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3 to use Node.js 20
      with:
        path: swift-srt

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        node-version: '20.x'  # Ensure using Node.js 20

    - name: Build Documentation
      run: |
        cd swift-srt
        swift build --target swift-srt --configuration debug
        xcodebuild docbuild -scheme swift-srt -destination generic/platform=iOS
        cp -R build/Build/Products/Debug-iphoneos/swift-srt.doccarchive ../docs
        $(xcrun --find docc) process-archive transform-for-static-hosting ../docs/swift-srt.doccarchive --output-path ../docs --hosting-base-path swift-srt/documentation/swiftsrt
